### PR TITLE
Add title to iframes.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hehe, I always use multiple tools, Lighthouse, HTML_Codesniffer, HTML validator, gtmetrix etc.

Should we do the same for the YouTube videos too?

**Comment by MartijnCuppens** [comment]
Yup, should we make it possible to add separate titles to all video's or shall we use the same title for all video's?

**Comment by XhmikosR** [comment]
I think the simplest solution would be to use the same title for now.

**Comment by XhmikosR** [comment]
Pushed, @MartijnCuppens let me know.

**Comment by MartijnCuppens** [comment]
Looks ok!

**Pull request merged**
