### PR TITLE
3.3.7 released blog post

### PR DESCRIPTION
**Pull request by jdorfman**

### CODE REVIEW

**Comment by cvrebert** [comment]
Superb!

**Comment by cvrebert** [comment]
@mdo Swap in the music video of your choice at your leisure :metal:

**Comment by jdorfman** [comment]
@cvrebert I did. I was feeling Heart... =)

**Comment by mdo** [comment]
Heading into the office now; can review in 10 mins.

**Comment by mkurz** [comment]
Does "Added support for jQuery 3" mean jQuery 3.x? Because there is jQuery 3.1 already.

**Comment by cvrebert** [comment]
@mkurz jQuery follows SemVer now. So any jQuery version beginning with `3.` should work.

**Comment by mkurz** [comment]
@cvrebert Thanks for clarification.

**Pull request merged**
