### PR TITLE
Add post about NO CARRIER

### PR DESCRIPTION
**Pull request by cvrebert**
CC: @twbs/team for review

Also, my google-fu fails me when trying to search for '80 music videos based on their lyrics. So anyway, in the unlikely event that @mdo can't find something better, here are a couple possible video choices:
* Lake Koast Feat. Pretty Pretty & Malik - "Shut It Down": https://www.youtube.com/watch?v=xsH_kPUYOnE
* *The Closer* promo: https://www.youtube.com/watch?v=QLK_dIPe6V4

### CODE REVIEW

**Comment by cvrebert** [comment]
@mdo Pingity-ping

**Comment by cvrebert** [comment]
@mdo Ready for final review, and video (although I'd be fine with not having one)

**Comment by mdo** [comment]
Twerked a few things and added the video :D.

**Comment by cvrebert** [comment]
Looks good! I'll squash and merge this bad boy.

**Comment by cvrebert** [comment]
@mdo Done! Can you tweet it? Thanks again man.

**Comment by mdo** [comment]
Was already on it :D.

**Comment by cvrebert** [comment]
:sparkling_heart:

**Comment by adammacias** [comment]
Published [on Facebook](https://www.facebook.com/getbootstrap/posts/537973553020906) :+1:

**Comment by cvrebert** [comment]
O_O

**Pull request merged**
