### PR TITLE
v3.3.2 post

### PR DESCRIPTION
**Pull request by cvrebert**
CC: @mdo @twbs/team @patrickhlauke

### CODE REVIEW

**Comment by cvrebert** [comment]
@mdo LGTY? We're also gonna need a music video :grin: :guitar:

**Comment by patrickhlauke** [comment]
if we're after 90s cheese...a few humble suggestions from my own misspent youth...

https://www.youtube.com/watch?v=8DzGgIURySI
https://www.youtube.com/watch?v=18W9WYw9HaA
https://www.youtube.com/watch?v=DfdkKYHlZp4
https://www.youtube.com/watch?v=7sPUpKGI1Z4
https://www.youtube.com/watch?v=9I5iugfTiIk
https://www.youtube.com/watch?v=i0cjGVpKLd4
https://www.youtube.com/watch?v=i0cjGVpKLd4

**Comment by patrickhlauke** [comment]
late addition (which according to my mate bruce lawson is my signature "i love fucking dolphins" song...) https://www.youtube.com/watch?v=z1Xztbywbl0

**Comment by mdo** [comment]
Got a video picked and it'll be ready tomorrow morning to push (changes are local to maintain maximum surprise for now :wink:).

**Comment by mdo** [comment]
Thanks so much for doing this, @cvrebert! If you're okay with it, I'd like to put your name first on the blog post. It's a small thing, but it'd be more accurate :).

**Comment by mdo** [comment]
And @patrickhlauke not bad suggestions, but I've had a video in mind for awhile :D.

**Comment by patrickhlauke** [comment]
no worries, i had my own fun anyway finding them on the 'tube :)

**Comment by mdo** [comment]
<3

**Comment by cvrebert** [comment]
:tada:

**Pull request merged**
